### ISSUE TITLE
Initializing multiple LDClients

### ISSUE THREAD

**Issue by BigLato** [launchdarkly/c-client#16]
I'm curious why there is a restriction in creating multiple LDClients per service. It does not seem out of the norm to have larger services need access to multiple LaunchDarkly projects. This is not an issue with the C# client as my company is utilizing this functionality. 

Would it be possible to make this functionality available?

**Comment by hroederld** [comment]
Hello BigLato!

For your intended use case do you need to use multiple mobile keys and multiple concurrent users, or multiple mobile keys targeting a single user?

Thanks!

**Comment by BigLato** [comment]
Multiple mobile keys targeting a single user. We have not played around with users much (especially since there was no C SDK 😄) so we have not had a use case for multiple users yet. Here is a snippet of something I was trying to do. In an single service, multiple mobile keys could be used which would need a new client.
```
static LDClient* get_client(const std::string& relay_url, const std::string& mobile_key)
{
	static std::unordered_map<std::string, LDClient*> 
		LDClientMap;

	// Look in map to see if client is already initialized
	if (LDClientMap.find(mobile_key) == LDClientMap.end())
	{
		// Client is not found so create add it to the map
		const uint32_t max_wait_milliseconds = 10 * 100;
		const auto config = LDConfigNew(mobile_key.c_str());
		const auto user = LDUserNew("default");
		LDConfigSetStreamURI(config, relay_url.c_str());
		if (getenv("LD_CLIENT_LOGGING") != nullptr)
			LDSetLogFunction(LD_LOG_TRACE, logger);

		auto client = new LDClient();
		client = LDClient::Init(config, user, max_wait_milliseconds);
		LDClientMap.insert(std::make_pair(mobile_key, client));
	}

	return LDClientMap.at(mobile_key);
}
```

**Comment by hroederld** [comment]
We have a specification for the client-side SDKs (such as this one) to support multiple environments. It has been implemented for mobile SDKs (such as Android), but does not yet exist in this SDK.

It allows targeting of a single user against multiple environments (mobile keys), and looks very similar to the code you have posted above. You can use other features provided by LD to achieve a similar result depending on how you organize your project, and we generally discourage multiple clients.

I will get started on multiple environments support for this SDK.

**Comment by hroederld** [comment]
Hi @BigLato thanks for your patience!

We updated this SDK to support usage of multiple environments: https://github.com/launchdarkly/c-client/releases/tag/1.2.0

When preparing your `LDConfig` you can add multiple secondary environments with `bool LDConfigAddSecondaryMobileKey(LDConfig *config, const char *name, const char *key);`. For example `LDConfigAddSecondaryMobileKey(myConfig, "team2", "********")`. You can then get that environment with `LDClientGetForMobileKey("team2")`. Operations such as flushing and switching users will apply to all environments.

**Comment by BigLato** [comment]
Perfect, I'll pull this down and give it a shot. Thank you for adding this so quickly!

**Comment by BigLato** [comment]
Hi @hroederld. I may have prematurely closed this ticket and am having trouble getting the mobile key after adding secondary keys. When I try to get the environment using ```LDClientGetForMobileKey```, I'm getting a 401. I verified the same test works without the using the new functions. Could this be because we are using a Relay?
```
LD: about to call connection handle callback
LD: finished calling connection handle callback
LD: curl response code 401
LD: mobile key not authorized, streaming failed
LD: killing thread LDi_bgfeaturestreamer
```

**Comment by hroederld** [comment]
@BigLato I tested the multi-environments functionality again and was not able to reproduce the issue. Are you sure that you are using multiple environments correctly? Let me provide a more complete example:

```
    LDConfig *config = LDConfigNew("mob-1******************");
    LDConfigAddSecondaryMobileKey(config, "secondary", "mob-2******************");

    LDUser *user = LDUserNew("biglato@example.com");

    LDClient *primary = LDClientInit(config, user, 3000);
    LDClient *secondary = LDClientGetForMobileKey("secondary");

    bool b1 = LDBoolVariation(primary, "my-feature-key", false);
    bool b2 = LDBoolVariation(secondary, "my-feature-key", false);
```

Do you have any additional information about your specific configuration? If you have information that cannot be shared in a public setting feel free to file a ticket referencing this issue.

**Comment by hroederld** [comment]
Additionally is it possible that the extra mobile key was not added to the Relay configuration? Each environment must be explicitly configured.

**Comment by BigLato** [comment]
Ah, I see what I was doing wrong. I was unsure how the "primary" client worked with the secondary and wasn't defining one or duplicating the key as a secondary. This cleared up my issues. Thanks for looking!
