### ISSUE TITLE
LDClient interference with cJSON versions

### ISSUE THREAD

**Issue by BigLato** [launchdarkly/c-client#17]
I have been trying to implement the C SDK and ran into an issue in one of the solutions. Initializing the client fails in LDi_clientsetflags when checking if payload->type is a cJSON_Object (I get the error message "LDi_clientsetflags did not get object"). 

I believe the issue is the c-client and my solution have different cJSON files. I noted that there is a property on the LDClient that has a cJSON type meaning the interface relies on a version of cJSON. Is there a reason for passing an cJSON type instead of a safer type (like a char*)? 

I attached the version of cJSON currently used in my solution so the bug can be duplicated. Let me know if you'd like more information.

[cJSON.zip](https://github.com/launchdarkly/c-client/files/3069570/cJSON.zip)

**Comment by hroederld** [comment]
Hi BigLato.

Are you statically or dynamically linking the SDK?

We don't have cJSON exposed anywhere in the public API, however the symbols still exist inside the library. If you dynamically link the library there should be no issue with symbol conflicts. See `ldapi.def` for the exposed symbol table.

There is not really a good way to consistently hide symbols inside a static library, which means if anyone uses a different version of Curl / cJSON in their executable there can be issues.

**Comment by BigLato** [comment]
I am linking the library dynamically into a .so to be used by an executable.

I also want to point out that cJSON is exposed by the LDClient for the property eventArray (see `ldinternal.h`).

**Comment by hroederld** [comment]
>I am linking the library dynamically into a .so to be used by an executable.
Ah a `.so` I was assuming you were on windows (in reference to `ldapi.def`). We are probably exporting more symbols than intended on POSIX then. I should be able to do a patch version and fix this quickly.

> I also want to point out that cJSON is exposed by the LDClient for the property eventArray
Everything in the public API goes through a pointer and should be basically opaque as far as the API / user / linker is concerned.

**Comment by hroederld** [comment]
@BigLato we have a new patch version https://github.com/launchdarkly/c-client/releases/tag/1.2.1

I verified that only the public API is exported by shared libraries in `1.2.1`. Try it out and let me know how that goes for you.

Thanks!

**Comment by BigLato** [comment]
@hroederld the patch resolved issue I had with the cJSON library though I now get an undefined reference for `LDSetLogFunction` when linking with ldapiplus. Definitely not a deal-breaker but something I wanted to point out.

**Comment by hroederld** [comment]
@BigLato we have a new patch version https://github.com/launchdarkly/c-client/releases/tag/1.2.2

Thanks for catching this!

**Comment by hroederld** [comment]
@BigLato If you have had a chance to try out the recent releases is your issue resolved?

**Comment by BigLato** [comment]
@hroederld Sorry for the delay. I had some issues and wanted to be sure the right version was being packaged. The log function is working as expected. Thanks again!
