### ISSUE TITLE
New line "\n" at the end of log messages is superfluous

### ISSUE THREAD

**Issue by eakraly** [launchdarkly/c-client#5]
New line is something that is very much depends on logging system. Practically any logging mechanism which not printf automatically add new line (so we get 2). 
And if it is not file based logging system or the format is {Key,Value}  then again new line superfluous.

**Comment by eli-darkly** [comment]
Correct. We've fixed this for the next release. I'll close this issue when the fix is available.

**Comment by eli-darkly** [comment]
This has been fixed in beta release 3.
