### ISSUE TITLE
Decrease initialization time

### ISSUE THREAD

**Issue by theCampbell** [launchdarkly/c-client#7]
We met a LD client initialization timing issue during program starting. It will cost about 7 seconds for the LD client initialization process. As our program need to use some feature flag during program starting. Is there any way to reduce the initialization time? I got c-sdk uses a background thread to get stream to initialize the LD client. In multi-thread environment, is it possible to promote priority of the stream thread for speed initializing process?

**Comment by eli-darkly** [comment]
Seven seconds is much longer than expected. I wouldn't expect that the thread priority would be a major factor here (the stream thread isn't really doing much other than waiting on I/O) but it's hard to say. Can you tell us more about the environment you're running in?

**Comment by Fred3773** [comment]
Hi Eli,

We met this issue in multi-thread environment. Our program has quite some executing thread during program starting and running. And in our running environment, I got the initializing process cost about 7 seconds. And sometimes, it may cost more 15 seconds. Not sure whether there is a good way to solve it.

Thanks,
Fred

**Comment by hroederld** [comment]
Unable to replicate, and no further information, closing this issue for now.

Thanks!
